name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-bigquery-microservice .

    - name: Push Docker image to GCR
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-bigquery-microservice

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-bigquery-microservice \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-bigquery-microservice \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
